baseURL:  ''
languageCode: 'en-us'
title: 'Pritpal Singh'
theme: "PaperMod"

# enableInlineShortcodes: true
# enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false
# enableEmoji: true
# pygmentsUseClasses: true

languages:
  en:
    languageName: "English"
    weight: 1
    # taxonomies:
    #   category: categories
    #   tag: tags
    #   series: series
    menu:
      main:
        # -name: Home
        #   url: "https://www.amazon.in/"
        #   weight: 10
        - name: About Me
          url: about_me/
          weight: 20
        - name: Projects
          url: /projects
          weight: 30
        - name: Tags
          url: /tags
          weight: 40
        # - name: Posts
        #   url: /posts
        #   weight: 40

params:
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  # ShowToc: true
  # ShowWordCount: true
  # ShowShareButtons: true
  # ShowPostNavLinks: true
  # ShowRssButtonInSectionTermList: true
  # ShowRssButtonInSectionList: true
  # ShowRssButtonInHomePage: true
  # ShowBrandIcon: true
  # ShowEditPageButtons: true
  # ShowComments: true
  # ShowLastmod: true
  # ShowRelatedPosts: true
  # ShowSearch: true
  ShowTags: true
  # ShowTaxonomyCloud: true
  # ShowPagination: true
  # ShowReadingTime: true
  # ShowShareButtons: true

  # home: "content/index.md"

  assets:
    favicon: "sikh.png"
    favicon16x16: "sikh.png"
    favicon32x32: "sikh.png"
    apple_touch_icon: "sikh.png"
    safari_pinned_tab: "sikh.png"
    theme_color: "#2e2e33"
    msapplication_TileColor: "#2e2e33"

  mainSections:
    - Projects
    - About Me

  
  homeInfoParams:
    title: " Hi, I'm Pritpal👋"
    content: "  ##  A Computer Science Student & an ML Enthusiast!
    

    • I'm thinking of training a model to detect dad jokes. It'll have to have a 'pun'-detection layer

    
    • I will beat you at chess (unless you are good at chess)


    • I type 200 words a minute; still my girlfriend complains 'You code faster than you text me' 


    > `Actively seeking opportunities in Data Science & Machine Learning!`
    "

  socialIcons:
    - name: github
      title: See my latest projects on github
      url: "https://github.com/pritpalcodes"

    - name: linkedin
      title: See a more professional photo of me @ linkedin
      url: "https://www.linkedin.com/in/oye-pritpal/"
    
    - name: discord
      title: Even I am figuring out how to use Discord
      url: "https://discord.com/"
    
    - name: X
      title: Say hi on X/Twitter
      url: https://twitter.com/oye_pritpal

  