baseURL:  'https://ppcodes.netlify.app/'
languageCode: 'en-us'
title: 'Pritpal Singh'
theme: "PaperMod"

# enableInlineShortcodes: true
# enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false
# enableEmoji: true
# pygmentsUseClasses: true

languages:
  en:
    languageName: "English"
    weight: 1
    # taxonomies:
    #   category: categories
    #   tag: tags
    #   series: series
    menu:
      main:
        # -name: Home
        #   url: "https://www.amazon.in/"
        #   weight: 10
        - name: About Me
          url: about_me/
          weight: 20
        - name: Projects
          url: /projects
          weight: 30
        - name: Tags
          url: /tags
          weight: 40
        # - name: Posts
        #   url: /posts
        #   weight: 40

params:
  ShowBreadCrumbs: true
  ShowReadingTime: true
  # ShowShareButtons: true
  # ShowPostNavLinks: true
  ShowWordCount: true
  # ShowRssButtonInSectionTermList: true
  # ShowRssButtonInSectionList: true
  # ShowRssButtonInHomePage: true
  # ShowBrandIcon: true
  ShowCodeCopyButtons: true
  # ShowWordCount: true
  ShowToc: true
  ShowEditPageButtons: true
  # ShowComments: true
  # ShowLastmod: true
  # ShowRelatedPosts: true
  # ShowSearch: true
  ShowTags: true
  # ShowTaxonomyCloud: true
  # ShowPagination: true
  # ShowReadingTime: true
  # ShowShareButtons: true




  mainSections:
    - Projects
    - About Me
  
  homeInfoParams:
    title: " Hi, I'm Pritpal👋"
    content: "  ##  A Computer Science Student & an ML Enthusiast.
    
    • I type 250 words a minute, still my girlfriend complains 'You are not good with fingers!' Idk what else she wants? 😕


    • I will beat you at chess (unless you are good at chess). 


    • I'm thinking of training a model to detect dad jokes. It'll have to have a 'pun'-detection layer!


    "

  socialIcons:
    - name: github
      title: See my latest projects on github
      url: "https://github.com/pritpalcodes"
    - name: linkedin
      title: See a more professional photo of me @ linkedin
      url: "www.linkedin.com/in/oye-pritpal/"
    - name: discord
      title: Even I am figuring out how to use Discord
      url: "https://discord.com/"
    - name: X
      title: Say hi on X/Twitter
      url: https://twitter.com/oye_pritpal

  